site_name: Yummy's Docs
pages:
    - Home: index.md
    # - About: about.md
    - MySQL: mysql.md
    - Git: git.md
    - TCP: tcp.md
    - Linux: linux.md
    - BlockChain: blockchain.md
    - BRPC: brpc.md
    - 交易:
        - 技术指标: trade_index.md
    - 德扑: poker.md
