site_name: Yummy's Docs
pages:
    - Home: index.md
    # - About: about.md
    - MySQL: mysql.md
    - Git: git.md
    - TCP: tcp.md
    - Linux: linux.md
    - BlockChain: blockchain.md
    - BRPC: brpc.md
    - 交易:
        - 技术指标: trade_index.md
        - K 线: trade_k.md
        - 交易系统: trade_system.md
        - 量化: quant.md
        - 价值投资: invest.md
    - 德扑: poker.md
    - 阅读: book.md
    - 学习: learn.md

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# markdown_extensions:
#     - math
